<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- MCP -->
    <PackageReference Include="ModelContextProtocol" Version="0.1.0-preview.7" />
    
    <!-- LLamaSharp (Para rodar o GGUF) -->
    <PackageReference Include="LLamaSharp" Version="0.20.0" />
    <!--PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.20.0" /-->
    <PackageReference Include="LLamaSharp.Backend.Cuda12" Version="0.20.0" />

    
    <!-- Abstrações de IA para facilitar o Agent -->
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.4.0" />
  </ItemGroup>
</Project>
