name: Publicar Pacote NuGet
on:
  workflow_dispatch: # Permite que você clique em "Run workflow" manualmente na aba Actions do GitHub  
  release:
    types: [published]

jobs:
  build_and_publish:
    name: Build, Pack e Publish
    runs-on: ubuntu-latest
    
     # GARANTA QUE ESSAS TRÊS PERMISSÕES ESTÃO EXATAMENTE ASSIM:
    permissions:
      id-token: write    # Necessário para o Trusted Publishing do NuGet
      contents: read     # CORREÇÃO: Dá permissão para ler o repositório privado
      packages: write    # Opcional (bom deixar caso use o GitHub Packages)

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          # ISSO RESOLVE O ERRO: Diz ao Git para clonar de forma anônima, 
          # já que seu repositório é público e não precisa de senhas/tokens.
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Altere para a versão do seu .NET

      - name: Restaurar dependências
        run: dotnet restore

      - name: Criar Pacote (Pack)
        run: dotnet pack Wolfish.Maia/Wolfish.Maia.csproj -c Release --output ./nupkg

      - name: Publicar no NuGet
        uses: NuGet/setup-nuget@v2

        # ESTA ETAPA FAZ A MÁGICA DO TRUSTED PUBLISHING FUNCIONAR
      - name: Autenticar no NuGet via Trusted Publishing
        uses: NuGet/login@v1
        id: nuget_login
        with:
          # ADICIONE ESTA LINHA ABAIXO:
          user: renatolobojr

      - name: Enviar Pacote (Push)
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key "${{ steps.nuget_login.outputs.token }}" --skip-duplicate
